### ISSUE TITLE
Not showing up under the Dashboard->Services

### ISSUE THREAD

**Issue by EugenMayer** [EugenMayer/tinc-opnsense#1]
Eventhough the plugin has https://github.com/EugenMayer/tinc-opnsense/blob/master/security/tinccustom/src/opnsense/service/conf/actions.d/actions_tincdcustom.conf in place, the service does not show up in the Services section.

There is a proper RC script https://github.com/EugenMayer/tinc-opnsense/blob/master/security/tinccustom/src/etc/rc.d/opnsense-tincdcustom also

**Comment by fraenki** [comment]
~I'm not sure what you mean by saying "the services does not show up". Do you refer to the "Services" list/widget on the dashboard?~

I think your plugin lacks the required legacy glue, see this example:
https://github.com/opnsense/plugins/blob/master/net/haproxy/src/etc/inc/plugins.inc.d/haproxy.inc#L48-L70

**Comment by EugenMayer** [comment]
@fraenki thank you, worked out exactly the way you expected it - though i have one issue left with this widget then https://github.com/EugenMayer/tinc-opnsense/issues/2
